services:
  # Nginx Proxy Manager
  npm:
    image: hub.rat.dev/jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"  # 管理界面
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt

  nvim:
    image: lerkobba/nvim
    container_name: nvim-lerko
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/workspace
      # Go 缓存持久化
      - go-mod-cache:/root/go/pkg/mod
      - cache:/root/.cache
    tty: true
    stdin_open: true
  syncclipboard:
    image: hub.rat.dev/jericx/syncclipboard-server
    container_name: syncclipboard
    restart: unless-stopped
    network_mode: host

volumes:
  go-mod-cache:
  cache:
  workspace:
  npm-data:
  npm-letsencrypt:
