services:
  # Nginx Proxy Manager
  npm:
    image: hub.rat.dev/jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"  # 管理界面
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  nvim:
    image: lerkobba/nvim
    container_name: nvim
    restart: unless-stopped
    command: ["python3", "/root/.local/bin/syncclipboard_client.py", "--url", "http://syncclipboard:5033", "--username", "your_username", "--password", "your_password", "--interval", "1"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/workspace
      # Go 缓存持久化
      - go-mod-cache:/root/go/pkg/mod
      - cache:/root/.cache
    tty: true
    stdin_open: true
    networks:
      - app-network

  syncclipboard:
    image: hub.rat.dev/jericx/syncclipboard-server
    container_name: syncclipboard
    restart: unless-stopped
    volumes:
      - syncclipboard-data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  go-mod-cache:
  cache:
  workspace:
  npm-data:
  npm-letsencrypt:
  syncclipboard-data:
